services:
  gayadi-be:
    image: gayadi-cr.kr.ncr.ntruss.com/gayadi-be:latest
    container_name: gayadi-be-container

    ports:
      - "8080:8080"

    env_file:
      - /home/ubuntu/gayadi/.env

    restart: unless-stopped