spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${db_password:${DB_PASSWORD:}}
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: false
springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}

server:
  forward-headers-strategy: framework

management:
  endpoint:
    health:
      show-details: never
