-- Android 여행 기능에서 사용하는 날짜 조율, 경비, 공지, 문의 도메인

CREATE TABLE trip_date_availability_submissions (
    trip_id       BIGINT    NOT NULL,
    user_id       BIGINT    NOT NULL,
    submitted_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_trip_date_submission PRIMARY KEY (trip_id, user_id),
    CONSTRAINT fk_date_submission_participant
        FOREIGN KEY (trip_id, user_id) REFERENCES trip_participants (trip_id, user_id)
        ON DELETE CASCADE
);

CREATE TABLE trip_date_availability (
    trip_id         BIGINT    NOT NULL,
    user_id         BIGINT    NOT NULL,
    available_date  DATE      NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_trip_date_availability PRIMARY KEY (trip_id, user_id, available_date),
    CONSTRAINT fk_date_availability_submission
        FOREIGN KEY (trip_id, user_id)
        REFERENCES trip_date_availability_submissions (trip_id, user_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_trip_date_availability_date
    ON trip_date_availability (trip_id, available_date, user_id);

CREATE TABLE trip_expenses (
    id                 BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id            BIGINT        NOT NULL,
    schedule_id        BIGINT,
    title              VARCHAR(100)  NOT NULL,
    memo               VARCHAR(1000) NOT NULL DEFAULT '',
    amount             BIGINT        NOT NULL CHECK (amount > 0),
    payer_user_id      BIGINT,
    expense_date       DATE          NOT NULL,
    expense_time       TIME          NOT NULL,
    category           VARCHAR(20)   NOT NULL
                           CHECK (category IN ('TOUR', 'MUSEUM', 'ACTIVITY', 'SHOPPING',
                                               'FOOD', 'LODGING', 'TRANSPORT', 'FLIGHT', 'OTHER')),
    payment_source     VARCHAR(20)   NOT NULL
                           CHECK (payment_source IN ('PERSONAL', 'SHARED_FUND')),
    receipt_image_uri  VARCHAR(1000),
    created_by         BIGINT        NOT NULL,
    created_at         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_trip_expense_payer CHECK (
        (payment_source = 'PERSONAL' AND payer_user_id IS NOT NULL)
        OR payment_source = 'SHARED_FUND'),
    CONSTRAINT fk_trip_expense_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
    CONSTRAINT fk_trip_expense_schedule FOREIGN KEY (schedule_id)
        REFERENCES travel_plan_items (id) ON DELETE SET NULL,
    CONSTRAINT fk_trip_expense_payer FOREIGN KEY (payer_user_id) REFERENCES users (id),
    CONSTRAINT fk_trip_expense_creator FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE TABLE trip_expense_participants (
    expense_id  BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    CONSTRAINT pk_trip_expense_participant PRIMARY KEY (expense_id, user_id),
    CONSTRAINT fk_expense_participant_expense FOREIGN KEY (expense_id)
        REFERENCES trip_expenses (id) ON DELETE CASCADE,
    CONSTRAINT fk_expense_participant_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_trip_expenses_trip_date
    ON trip_expenses (trip_id, expense_date, expense_time, id);
CREATE INDEX idx_trip_expense_participants_user
    ON trip_expense_participants (user_id, expense_id);

CREATE TABLE trip_shared_fund_contributions (
    id          BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id     BIGINT    NOT NULL,
    amount      BIGINT    NOT NULL CHECK (amount > 0),
    created_by  BIGINT    NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_shared_fund_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
    CONSTRAINT fk_shared_fund_creator FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE INDEX idx_shared_fund_trip ON trip_shared_fund_contributions (trip_id, id);

CREATE TABLE notices (
    notice_id      VARCHAR(50)   NOT NULL PRIMARY KEY,
    title          VARCHAR(200)  NOT NULL,
    category       VARCHAR(20)   NOT NULL CHECK (category IN ('UPDATE', 'NOTICE', 'EVENT')),
    version        VARCHAR(30),
    published_at   TIMESTAMP     NOT NULL,
    summary        VARCHAR(1000) NOT NULL,
    sections       TEXT          NOT NULL,
    pinned         BOOLEAN       NOT NULL DEFAULT FALSE,
    status         VARCHAR(20)   NOT NULL DEFAULT 'PUBLISHED'
                       CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_notices_publication
    ON notices (status, pinned, published_at, notice_id);

CREATE TABLE support_inquiries (
    id             BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT        NOT NULL,
    category       VARCHAR(20)   NOT NULL CHECK (category IN ('BUG', 'FEATURE', 'ACCOUNT', 'ETC')),
    title          VARCHAR(100)  NOT NULL,
    message        VARCHAR(3000) NOT NULL,
    contact_email  VARCHAR(255)  NOT NULL,
    status         VARCHAR(20)   NOT NULL DEFAULT 'RECEIVED'
                       CHECK (status IN ('RECEIVED', 'IN_REVIEW', 'ANSWERED', 'CLOSED')),
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_support_inquiry_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_support_inquiries_user
    ON support_inquiries (user_id, created_at, id);

INSERT INTO notices
    (notice_id, title, category, version, published_at, summary, sections, pinned)
VALUES
    ('welcome-2026', '가야디 여행 기능 안내', 'UPDATE', '1.0.0', CURRENT_TIMESTAMP,
     '여행 일정, 경로, 경비와 현장 상황 대응 기능을 한곳에서 사용할 수 있습니다.',
     '[{"title":"여행 준비","body":"여행을 만들고 참여자를 초대한 뒤 가능한 날짜를 함께 조율할 수 있습니다."},{"title":"여행 중","body":"날씨와 교통 상황에 따라 대체 장소와 경로를 제안합니다."}]',
     TRUE);
