-- GAYADI Schema V1 — DDL 기반 22개 테이블
-- H2(PostgreSQL 모드) 및 PostgreSQL 호환: IDENTITY, CHECK, TEXT(JSON) 사용

-- 1. 사용자
CREATE TABLE users (
    id              BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname        VARCHAR(30)  NOT NULL,
    introduction    VARCHAR(100),
    profile_image_url VARCHAR(500),
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE'
                        CHECK (status IN ('ACTIVE', 'WITHDRAW', 'SUSPENDED')),
    last_login_at   TIMESTAMP,
    created_at      Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at      Timestamp
);

-- 2. 지역
CREATE TABLE regions (
    region_id       BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(50)  NOT NULL,
    latitude        DECIMAL(10, 7),
    longitude       DECIMAL(10, 7),
    created_at      Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. 설문지
CREATE TABLE surveys (
    id              BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    description     VARCHAR(500),
    version         INT          NOT NULL,
    status          VARCHAR(20)  NOT NULL
                        CHECK (status IN ('DRAFT', 'ACTIVE', 'INACTIVE')),
    created_at      Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 4. 설문 문항
CREATE TABLE survey_questions (
    id              BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id       BIGINT       NOT NULL,
    question_text   VARCHAR(500) NOT NULL,
    axis_type       VARCHAR(30)  NOT NULL
                        CHECK (axis_type IN ('TRAVEL_PREPARATION', 'PLACE_PREFERENCE', 'TRAVEL_STYLE')),
    sequence_no     INT          NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE'
                        CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_at      Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_question_survey FOREIGN KEY (survey_id) REFERENCES surveys (id)
);

-- 5. 설문 문항 선택지
CREATE TABLE survey_question_options (
    id              BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id     BIGINT       NOT NULL,
    option_text     VARCHAR(500) NOT NULL,
    option_code     VARCHAR(50),
    score_value     INT          NOT NULL,
    sequence_no     INT          NOT NULL,
    created_at      Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_option_question FOREIGN KEY (question_id) REFERENCES survey_questions (id)
);

-- 6. places
CREATE TABLE places (
    id              BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id   BIGINT,
    trip_id         BIGINT,
    source          VARCHAR(20)  NOT NULL
                        CHECK (source IN ('TOUR_API', 'NAVER', 'KAKAO', 'USER', 'TRIP')),
    visibility      VARCHAR(20)  NOT NULL DEFAULT 'PUBLIC'
                        CHECK (visibility IN ('PUBLIC', 'PRIVATE', 'TRIP_ONLY')),
    source_place_id VARCHAR(255),
    name            VARCHAR(200) NOT NULL,
    category        VARCHAR(30)  NOT NULL
                        CHECK (category IN ('ATTRACTION', 'RESTAURANT', 'ACCOMMODATION', 'CAFE', 'SHELTER', 'CULTURE', 'SHOPPING', 'ETC')),
    address         VARCHAR(500),
    road_address    VARCHAR(500),
    latitude        DECIMAL(10, 7) NOT NULL,
    longitude       DECIMAL(10, 7) NOT NULL,
    region_id       BIGINT       NOT NULL,
    phone           VARCHAR(50),
    homepage_url    VARCHAR(1000),
    image_url       VARCHAR(1000),
    indoor          BOOLEAN,
    basic_info      TEXT,
    operating_hours TEXT,
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE'
                        CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELETED')),
    created_at      Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_place_owner FOREIGN KEY (owner_user_id) REFERENCES users (id),
    CONSTRAINT fk_place_region FOREIGN KEY (region_id) REFERENCES regions (region_id)
);

-- 7. 여행
CREATE TABLE trips (
    id              BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id        BIGINT       NOT NULL,
    title           VARCHAR(100) NOT NULL,
    description     VARCHAR(500),
    start_date      DATE         NOT NULL,
    end_date        DATE         NOT NULL,
    departure_mode  VARCHAR(20) NOT NULL
                        CHECK (departure_mode IN ('TOGETHER', 'SEPARATE')),
    meeting_at      Timestamp,
    meeting_place_id BIGINT,
    region_id       BIGINT       NOT NULL,
    trip_preferences TEXT,
    status          VARCHAR(20)  NOT NULL DEFAULT 'PLANNING'
                        CHECK (status IN ('PLANNING', 'IN_PROGRESS', 'COMPLETED', 'CANCELED')),
    max_members     INT,
    started_at      Timestamp,
    ended_at        Timestamp,
    created_at      Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at      Timestamp,
    CONSTRAINT fk_trip_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_trip_region FOREIGN KEY (region_id) REFERENCES regions (region_id),
    CONSTRAINT fk_trip_meeting_place FOREIGN KEY (meeting_place_id) REFERENCES places (id)
);

-- places.trip_id → trips 순환 FK (trips 생성 후 추가)
ALTER TABLE places ADD CONSTRAINT fk_place_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE;

-- 8. 여행 참여자
CREATE TABLE trip_participants (
    id                  BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id             BIGINT       NOT NULL,
    user_id             BIGINT       NOT NULL,
    role                VARCHAR(10)  NOT NULL
                            CHECK (role IN ('OWNER', 'MEMBER')),
    status              VARCHAR(20)  NOT NULL DEFAULT 'JOINED'
                            CHECK (status IN ('JOINED', 'LEFT', 'REMOVED')),
    departure_place_id  BIGINT,
    return_place_id     BIGINT,
    route_preferences   TEXT,
    joined_at           Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at             Timestamp,
    created_at          Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_participant_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
    CONSTRAINT fk_participant_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_participant_dep_place FOREIGN KEY (departure_place_id) REFERENCES places (id),
    CONSTRAINT fk_participant_ret_place FOREIGN KEY (return_place_id) REFERENCES places (id),
    CONSTRAINT uk_trip_participant UNIQUE (trip_id, user_id)
);

-- 9. 여행 초대
CREATE TABLE travel_invitations (
    id                BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id           BIGINT       NOT NULL,
    inviter_id        BIGINT       NOT NULL,
    invitee_user_id  BIGINT,
    invite_code       VARCHAR(100) NOT NULL,
    status            VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                        CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELED', 'EXPIRED')),
    expires_at        Timestamp    NOT NULL,
    accepted_at       Timestamp,
    rejected_at       Timestamp,
    canceled_at       Timestamp,
    created_at        Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_invitation_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
    CONSTRAINT fk_invitation_inviter FOREIGN KEY (inviter_id) REFERENCES users (id),
    CONSTRAINT fk_invitation_invitee FOREIGN KEY (invitee_user_id) REFERENCES users (id)
);

-- 10. 여행 일정
CREATE TABLE travel_plans (
    id                  BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id             BIGINT       NOT NULL,
    plan_date           DATE         NOT NULL,
    day_number          INT          NOT NULL,
    title               VARCHAR(100) NOT NULL,
    description         VARCHAR(500),
    source_type         VARCHAR(10)  NOT NULL
                            CHECK (source_type IN ('MANUAL', 'AI')),
    status              VARCHAR(20)  NOT NULL DEFAULT 'DRAFT'
                            CHECK (status IN ('DRAFT', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELED')),
    preference_snapshot TEXT,
    created_by          BIGINT       NOT NULL,
    version             INT          NOT NULL DEFAULT 0,
    created_at          Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_plan_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
    CONSTRAINT fk_plan_creator FOREIGN KEY (created_by) REFERENCES users (id)
);

-- 11. 여행 일정 항목
CREATE TABLE travel_plan_items (
    id              BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id         BIGINT       NOT NULL,
    place_id        BIGINT,
    item_type       VARCHAR(20)  NOT NULL
                        CHECK (item_type IN ('PLACE', 'MEAL', 'ACCOMMODATION', 'TRANSPORT', 'FREE_TIME', 'CUSTOM')),
    title           VARCHAR(200) NOT NULL,
    description     VARCHAR(500),
    sequence_no     INT          NOT NULL,
    planned_start   Timestamp,
    planned_end     Timestamp,
    status          VARCHAR(20)  NOT NULL DEFAULT 'PLANNED'
                        CHECK (status IN ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', 'CANCELED')),
    estimated_cost  DECIMAL(15, 2),
    memo            VARCHAR(500),
    created_at      Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_item_plan FOREIGN KEY (plan_id) REFERENCES travel_plans (id) ON DELETE CASCADE,
    CONSTRAINT fk_item_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT uk_plan_item_sequence UNIQUE (plan_id, sequence_no)
);

-- 12. 여행 경로
CREATE TABLE travel_routes (
    id                  BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id             BIGINT       NOT NULL,
    member_id           BIGINT,
    from_plan_item_id   BIGINT,
    to_plan_item_id    BIGINT,
    phase               VARCHAR(15)  NOT NULL
                            CHECK (phase IN ('DEPARTURE', 'IN_TRIP', 'RETURN')),
    route_data          TEXT,
    transport_mode      VARCHAR(20)  NOT NULL
                            CHECK (transport_mode IN ('PUBLIC_TRANSIT', 'WALK', 'CAR', 'TAXI', 'BICYCLE', 'MIXED')),
    duration_minutes    INT,
    distance_meters     INT,
    transfer_count      INT,
    fare                DECIMAL(15, 2),
    status              VARCHAR(20)  NOT NULL DEFAULT 'RECOMMENDED'
                            CHECK (status IN ('RECOMMENDED', 'SELECTED', 'EXPIRED', 'CANCELED')),
    recommended_at      Timestamp,
    selected_at         Timestamp,
    created_at          Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_route_plan FOREIGN KEY (plan_id) REFERENCES travel_plans (id) ON DELETE CASCADE,
    CONSTRAINT fk_route_member FOREIGN KEY (member_id) REFERENCES trip_participants (id) ON DELETE CASCADE,
    CONSTRAINT fk_route_from_item FOREIGN KEY (from_plan_item_id) REFERENCES travel_plan_items (id),
    CONSTRAINT fk_route_to_item FOREIGN KEY (to_plan_item_id) REFERENCES travel_plan_items (id)
);

-- 13. 여행 준비물
CREATE TABLE travel_supplies (
    id                  BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id             BIGINT       NOT NULL,
    assigned_member_id BIGINT,
    plan_item_id        BIGINT,
    name                VARCHAR(100) NOT NULL,
    category            VARCHAR(20)
                            CHECK (category IN ('WASH', 'SLEEP', 'CLOTHING', 'ELECTRONICS', 'FOOD', 'DOCUMENTS', 'MEDICAL', 'MISC')),
    quantity            INT          NOT NULL DEFAULT 1,
    is_checked          BOOLEAN      NOT NULL DEFAULT FALSE,
    source_type         VARCHAR(20)  NOT NULL
                            CHECK (source_type IN ('MANUAL', 'DEFAULT', 'AI')),
    memo                VARCHAR(500),
    created_by          BIGINT       NOT NULL,
    checked_by          BIGINT,
    checked_at          Timestamp,
    created_at          Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_supply_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
    CONSTRAINT fk_supply_member FOREIGN KEY (assigned_member_id) REFERENCES trip_participants (id) ON DELETE CASCADE,
    CONSTRAINT fk_supply_item FOREIGN KEY (plan_item_id) REFERENCES travel_plan_items (id),
    CONSTRAINT fk_supply_creator FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_supply_checker FOREIGN KEY (checked_by) REFERENCES users (id)
);

-- 14. 설문 응시 및 결과
CREATE TABLE survey_attempts (
    id                  BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       NOT NULL,
    survey_id           BIGINT       NOT NULL,
    trip_id             BIGINT,
    status              VARCHAR(20)  NOT NULL
                            CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'CANCELED')),
    travel_prep_score   INT,
    place_pref_score    INT,
    travel_style_score  INT,
    preparation_type    VARCHAR(15)
                            CHECK (preparation_type IN ('PLANNED', 'SPONTANEOUS')),
    place_preference    VARCHAR(10)
                            CHECK (place_preference IN ('NATURE', 'CITY')),
    travel_style        VARCHAR(10)
                            CHECK (travel_style IN ('ACTIVE', 'RELAXED')),
    result_code         VARCHAR(5)
                            CHECK (result_code IN ('PNA', 'PNR', 'PCA', 'PCR', 'SNA', 'SNR', 'SCA', 'SCR')),
    started_at          Timestamp    NOT NULL,
    completed_at        Timestamp,
    updated_at          Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attempt_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_attempt_survey FOREIGN KEY (survey_id) REFERENCES surveys (id),
    CONSTRAINT fk_attempt_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE
);

-- 15. 문항별 응답
CREATE TABLE question_responses (
    id              BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id      BIGINT       NOT NULL,
    question_id     BIGINT       NOT NULL,
    option_id       BIGINT       NOT NULL,
    score_value     INT          NOT NULL,
    created_at      Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_response_attempt FOREIGN KEY (attempt_id) REFERENCES survey_attempts (id) ON DELETE CASCADE,
    CONSTRAINT fk_response_question FOREIGN KEY (question_id) REFERENCES survey_questions (id),
    CONSTRAINT fk_response_option FOREIGN KEY (option_id) REFERENCES survey_question_options (id)
);

-- 16. 이벤트 관측
CREATE TABLE event_observations (
    id                  BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id            BIGINT,
    region_id           BIGINT       NOT NULL,
    event_type          VARCHAR(20)  NOT NULL
                            CHECK (event_type IN ('WEATHER', 'CONGESTION', 'TRANSPORT', 'CLOSURE', 'DISASTER')),
    source              VARCHAR(50)  NOT NULL,
    external_event_id   VARCHAR(255),
    observed_at         Timestamp    NOT NULL,
    valid_from          Timestamp,
    valid_to            Timestamp,
    severity            VARCHAR(10)  NOT NULL
                            CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    normalized_data     TEXT,
    raw_payload         TEXT,
    created_at          Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_event_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT fk_event_region FOREIGN KEY (region_id) REFERENCES regions (region_id)
);

-- 17. AI 일정 변경 제안
CREATE TABLE ai_schedule_change_proposals (
    id                  BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id             BIGINT       NOT NULL,
    plan_id             BIGINT       NOT NULL,
    event_id            BIGINT,
    proposal_type       VARCHAR(30)  NOT NULL
                            CHECK (proposal_type IN ('WEATHER_CHANGE', 'CONGESTION_CHANGE', 'TRANSPORT_CHANGE', 'USER_REQUEST')),
    reason              VARCHAR(1000) NOT NULL,
    before_snapshot     TEXT         NOT NULL,
    after_snapshot      TEXT,
    status              VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                            CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'APPLIED', 'FAILED', 'REVERTED')),
    generated_at        Timestamp    NOT NULL,
    expires_at          Timestamp,
    decided_by          BIGINT,
    decided_at          Timestamp,
    applied_at          Timestamp,
    reverted_at         Timestamp,
    created_at          Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_proposal_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
    CONSTRAINT fk_proposal_plan FOREIGN KEY (plan_id) REFERENCES travel_plans (id) ON DELETE CASCADE,
    CONSTRAINT fk_proposal_event FOREIGN KEY (event_id) REFERENCES event_observations (id),
    CONSTRAINT fk_proposal_decider FOREIGN KEY (decided_by) REFERENCES users (id)
);

-- 18. 알림
CREATE TABLE notifications (
    id                  BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       NOT NULL,
    notification_type   VARCHAR(40)  NOT NULL,
    title               VARCHAR(200) NOT NULL,
    content             VARCHAR(1000) NOT NULL,
    trip_id             BIGINT,
    invitation_id       BIGINT,
    plan_id             BIGINT,
    plan_item_id        BIGINT,
    route_id            BIGINT,
    event_id            BIGINT,
    proposal_id         BIGINT,
    is_read             BOOLEAN      NOT NULL DEFAULT FALSE,
    read_at             Timestamp,
    sent_at             Timestamp,
    created_at          Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_notif_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
    CONSTRAINT fk_notif_invitation FOREIGN KEY (invitation_id) REFERENCES travel_invitations (id),
    CONSTRAINT fk_notif_plan FOREIGN KEY (plan_id) REFERENCES travel_plans (id),
    CONSTRAINT fk_notif_plan_item FOREIGN KEY (plan_item_id) REFERENCES travel_plan_items (id),
    CONSTRAINT fk_notif_route FOREIGN KEY (route_id) REFERENCES travel_routes (id),
    CONSTRAINT fk_notif_event FOREIGN KEY (event_id) REFERENCES event_observations (id),
    CONSTRAINT fk_notif_proposal FOREIGN KEY (proposal_id) REFERENCES ai_schedule_change_proposals (id)
);

-- 19. 사용자 기기
CREATE TABLE user_devices (
    id              BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    device_id       VARCHAR(255) NOT NULL,
    device_name     VARCHAR(100),
    platform        VARCHAR(10)  NOT NULL
                        CHECK (platform IN ('ANDROID', 'IOS', 'WEB')),
    push_enabled    BOOLEAN      NOT NULL DEFAULT TRUE,
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE'
                        CHECK (status IN ('ACTIVE', 'LOGGED_OUT')),
    last_active_at  Timestamp,
    created_at      Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_device_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_user_device UNIQUE (user_id, device_id)
);

-- 20. 소셜 로그인 계정
CREATE TABLE social_login_accounts (
    id                  BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       NOT NULL,
    provider            VARCHAR(20)  NOT NULL
                            CHECK (provider IN ('GOOGLE', 'KAKAO', 'NAVER')),
    provider_subject    VARCHAR(255) NOT NULL,
    provider_email      VARCHAR(255),
    provider_name       VARCHAR(100),
    linked_at           Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at       Timestamp,
    updated_at          Timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_social_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_provider_subject UNIQUE (provider, provider_subject)
);

-- 21. 사용자 선호 장소(찜)
CREATE TABLE user_favorite_places (
    user_id     BIGINT       NOT NULL,
    place_id    BIGINT       NOT NULL,
    memo        VARCHAR(500),
    created_at   Timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_favorite_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_favorite_place FOREIGN KEY (place_id) REFERENCES places (id) ON DELETE CASCADE,
    CONSTRAINT pk_favorite PRIMARY KEY (user_id, place_id)
);

-- 인덱스
CREATE INDEX idx_survey_questions_survey ON survey_questions (survey_id);
CREATE INDEX idx_question_options_question ON survey_question_options (question_id);
CREATE INDEX idx_places_region ON places (region_id);
CREATE INDEX idx_places_trip ON places (trip_id);
CREATE INDEX idx_trips_owner ON trips (owner_id);
CREATE INDEX idx_trips_region ON trips (region_id);
CREATE INDEX idx_trip_participants_trip ON trip_participants (trip_id);
CREATE INDEX idx_trip_participants_user ON trip_participants (user_id);
CREATE INDEX idx_travel_invitations_trip ON travel_invitations (trip_id);
CREATE INDEX idx_travel_plans_trip ON travel_plans (trip_id);
CREATE INDEX idx_travel_plan_items_plan ON travel_plan_items (plan_id, sequence_no);
CREATE INDEX idx_travel_routes_plan ON travel_routes (plan_id);
CREATE INDEX idx_travel_routes_member ON travel_routes (member_id);
CREATE INDEX idx_travel_supplies_trip ON travel_supplies (trip_id);
CREATE INDEX idx_survey_attempts_user ON survey_attempts (user_id);
CREATE INDEX idx_survey_attempts_trip ON survey_attempts (trip_id);
CREATE INDEX idx_question_responses_attempt ON question_responses (attempt_id);
CREATE INDEX idx_event_observations_place ON event_observations (place_id, observed_at);
CREATE INDEX idx_event_observations_region ON event_observations (region_id);
CREATE INDEX idx_proposals_trip ON ai_schedule_change_proposals (trip_id, status);
CREATE INDEX idx_notifications_user ON notifications (user_id, is_read);
CREATE INDEX idx_user_devices_user ON user_devices (user_id);
CREATE INDEX idx_social_accounts_user ON social_login_accounts (user_id);
