-- Android 앱 기능과 서버 저장 구조 정렬
-- H2 PostgreSQL 모드와 PostgreSQL에서 함께 사용하는 표준 SQL만 사용한다.

CREATE INDEX idx_travel_invitations_status_expiry
    ON travel_invitations (status, expires_at);
CREATE INDEX idx_travel_invitations_invitee_status
    ON travel_invitations (invitee_user_id, status);

ALTER TABLE travel_plan_items
    ADD COLUMN schedule_type VARCHAR(20) NOT NULL DEFAULT 'MAIN'
        CHECK (schedule_type IN ('MAIN', 'ALTERNATIVE'));
ALTER TABLE travel_plan_items
    ADD COLUMN is_visited BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE ai_schedule_change_proposals
    ADD COLUMN base_revision_no INT NOT NULL DEFAULT 0;
ALTER TABLE ai_schedule_change_proposals
    ADD COLUMN options_snapshot TEXT;
ALTER TABLE ai_schedule_change_proposals
    ADD COLUMN selected_option_key VARCHAR(50);

ALTER TABLE trips
    ADD COLUMN version INT NOT NULL DEFAULT 0;

CREATE TABLE trip_cities (
    id          BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id     BIGINT      NOT NULL,
    city_name   VARCHAR(50) NOT NULL,
    sequence_no INT         NOT NULL,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trip_city_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
    CONSTRAINT uk_trip_city_sequence UNIQUE (trip_id, sequence_no)
);

CREATE INDEX idx_trip_cities_trip ON trip_cities (trip_id);

-- 기존 여행도 앱에서 도시가 비지 않도록 대표 지역 이름을 첫 도시로 채운다.
INSERT INTO trip_cities (trip_id, city_name, sequence_no)
SELECT t.id, r.name, 1
FROM trips t
JOIN regions r ON r.region_id = t.region_id
WHERE NOT EXISTS (SELECT 1 FROM trip_cities tc WHERE tc.trip_id = t.id);

CREATE TABLE legal_documents (
    document_id        VARCHAR(50)  NOT NULL PRIMARY KEY,
    title              VARCHAR(100) NOT NULL,
    version            VARCHAR(20)  NOT NULL,
    effective_date     DATE         NOT NULL,
    publication_status VARCHAR(20)  NOT NULL,
    summary            VARCHAR(1000) NOT NULL,
    review_notice      VARCHAR(1000),
    sections           TEXT         NOT NULL,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE travel_personality_results (
    result_code      VARCHAR(5)   NOT NULL PRIMARY KEY,
    emoji            VARCHAR(20)  NOT NULL,
    name             VARCHAR(100) NOT NULL,
    summary          VARCHAR(500) NOT NULL,
    character_key    VARCHAR(50)  NOT NULL,
    hashtags         TEXT         NOT NULL,
    strengths        TEXT         NOT NULL,
    weaknesses       TEXT         NOT NULL,
    compatible_types TEXT         NOT NULL,
    travel_role      TEXT         NOT NULL,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 기존 3문항 설문의 의미와 과거 응답은 그대로 보존하고,
-- Android 앱의 9문항 정의는 새 설문 버전으로 등록한다.
UPDATE surveys
SET status = 'INACTIVE', updated_at = CURRENT_TIMESTAMP
WHERE id = 1;

INSERT INTO surveys
    (id, name, description, version, status, created_at, updated_at)
VALUES
    (2, '여행 성향 판단 설문조사', '재미로 알아보는 여행 성향 테스트', 2, 'ACTIVE',
     CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO survey_questions
    (id, survey_id, question_text, axis_type, sequence_no, status, created_at, updated_at)
VALUES
    (10, 2, '여행이 정해졌다! 가장 먼저 하는 일은?', 'TRAVEL_PREPARATION', 1, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (11, 2, '여행지에서 갑자기 비가 온다. 나는?', 'TRAVEL_PREPARATION', 2, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (12, 2, '마음에 든 장소를 만났다.', 'TRAVEL_PREPARATION', 3, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (13, 2, '여행 사진첩을 열면 더 많은 사진은?', 'PLACE_PREFERENCE', 4, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (14, 2, '다음 중 더 설레는 하루는?', 'PLACE_PREFERENCE', 5, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (15, 2, '여행지에서 ‘여기 오길 잘했다’ 싶은 순간은?', 'PLACE_PREFERENCE', 6, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (16, 2, '이상적인 여행지 오후 3시는?', 'TRAVEL_STYLE', 7, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (17, 2, '여행에서 ‘잘 놀았다’의 기준은?', 'TRAVEL_STYLE', 8, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (18, 2, '하루 일정의 밀도는?', 'TRAVEL_STYLE', 9, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO survey_question_options
    (id, question_id, option_text, option_code, score_value, sequence_no, created_at, updated_at)
VALUES
    (20, 10, '엑셀·노션에 일정표부터 짠다', 'P', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (21, 10, '일단 항공권만 끊고 나머진 나중에', 'S', -1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (22, 11, '미리 짜둔 실내 플랜 B로 전환', 'P', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (23, 11, '그때그때 즉흥으로 근처 아무 데나', 'S', -1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (24, 12, '아쉽지만 다음 일정이 있어 이동', 'P', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (25, 12, '계획이고 뭐고 눌러앉아 즐긴다', 'S', -1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (26, 13, '바다·산·노을 같은 자연 풍경', 'N', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (27, 13, '골목·건축물·카페·전시', 'C', -1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (28, 14, '숲길 걷고 계곡에 발 담그기', 'N', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (29, 14, '오래된 도심 골목과 갤러리 탐방', 'C', -1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (30, 15, '탁 트인 자연을 마주할 때', 'N', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (31, 15, '도시의 분위기·야경에 빠질 때', 'C', -1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (32, 16, '서핑·등산·자전거 등 몸 쓰는 활동', 'A', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (33, 16, '카페·숙소에서 늘어지게 휴식', 'R', -1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (34, 17, '평소 못 하던 활동으로 에너지 발산', 'A', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (35, 17, '아무것도 안 하고 푹 충전', 'R', -1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (36, 18, '부지런히 여러 곳, 알차게', 'A', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (37, 18, '한두 곳만 느긋하게', 'R', -1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 설문 결과의 배열과 객체는 Android 자료 형식을 잃지 않도록 JSON 문자열로 저장한다.
INSERT INTO travel_personality_results
    (result_code, emoji, name, summary, character_key, hashtags, strengths, weaknesses, compatible_types, travel_role)
VALUES
    ('PNA', '⛰️', '정상까지 계획대로, 등반잉', '코스도 체력도 미리 계산해두고 자연 속으로 뛰어드는 여행 스타일', 'character_pna', '["# 코스 설계","# 자연 정복","# 체력 만렙","# 안전 준비"]', '["등산로와 소요 시간을 미리 조사해요.","날씨와 장비까지 챙겨 안전하게 움직여요.","목표한 코스는 끝까지 완주해요.","자연 속에서도 알차게 하루를 채워요."]', '["일정이 밀리면 조급해질 수 있어요.","쉬어가는 순간을 놓치기 쉬워요.","동행의 체력을 고려하지 못할 수 있어요.","계획에 없던 풍경을 지나칠 수 있어요."]', '[{"code":"PNR","emoji":"🏞️","name":"한적한 곳만 골라, 힐링잉"},{"code":"SNA","emoji":"🏄","name":"일단 뛰어들어, 파도잉"}]', '{"icon":"🧭","title":"코스 대장","description":"목표와 이동 순서를 정리하고 모두가 안전하게 완주하도록 이끌어요."}'),
    ('PNR', '🏞️', '한적한 곳만 골라, 힐링잉', '미리 알아둔 조용한 자연에서 느긋하게 재충전하는 여행 스타일', 'character_pnr', '["# 사전 조사","# 한적한 곳","# 느긋 충전","# 쉼표 여행"]', '["붐비지 않는 시간대를 미리 알아봐요.","이동이 편한 숙소를 잘 골라요.","자연 속에서 깊게 쉬고 돌아와요.","무리한 일정 없이 컨디션을 지켜요."]', '["예상보다 사람이 많으면 실망할 수 있어요.","새로운 활동에 도전할 기회가 적어요.","일정이 여유로워 아쉬움이 남을 수 있어요.","즉흥적인 제안에 망설일 수 있어요."]', '[{"code":"PNA","emoji":"⛰️","name":"정상까지 계획대로, 등반잉"},{"code":"SNR","emoji":"🌅","name":"발길 닿는 대로, 노을잉"}]', '{"icon":"🌿","title":"쉼표 지킴이","description":"무리한 일정을 덜어내고 모두가 편안히 회복할 시간을 챙겨요."}'),
    ('PCA', '🏙️', '도시 구석까지 훑어, 완주잉', '가고 싶은 곳을 지도에 다 찍어두고 부지런히 누비는 여행 스타일', 'character_pca', '["# 동선 최적화","# 명소 완주","# 부지런 만렙","# 예약 철저"]', '["가고 싶은 곳을 지도에 미리 정리해요.","대중교통과 동선을 효율적으로 짜요.","하루에 여러 곳을 알차게 소화해요.","예약이 필요한 곳을 놓치지 않아요."]', '["일정이 빡빡해 지치기 쉬워요.","한 장소를 충분히 즐기지 못할 수 있어요.","예약이 엇갈리면 당황할 수 있어요.","쉬는 시간을 일정에서 빼먹기 쉬워요."]', '[{"code":"PCR","emoji":"🎨","name":"감성 스팟만 모아, 큐레잉"},{"code":"SCA","emoji":"🔥","name":"그날 끌리는 대로, 인싸잉"}]', '{"icon":"🗺️","title":"동선 설계자","description":"예약과 교통을 촘촘히 연결해 하루의 시간을 알차게 만들어요."}'),
    ('PCR', '🎨', '감성 스팟만 모아, 큐레잉', '미리 찾아둔 전시와 카페를 하루 두세 곳씩 천천히 음미하는 여행 스타일', 'character_pcr', '["# 전시 투어","# 카페 탐방","# 감성 수집","# 느긋 음미"]', '["취향에 맞는 장소를 잘 찾아내요.","하루 일정을 여유 있게 배치해요.","한 곳에서 깊이 있게 시간을 보내요.","사진과 기록으로 여행을 잘 남겨요."]', '["방문하는 장소 수가 적을 수 있어요.","취향 밖의 장소는 시도하지 않게 돼요.","기대했던 분위기가 아니면 아쉬워해요.","활동적인 일정에는 흥미가 덜해요."]', '[{"code":"PCA","emoji":"🏙️","name":"도시 구석까지 훑어, 완주잉"},{"code":"SCR","emoji":"☕","name":"골목 따라 흘러가, 유랑잉"}]', '{"icon":"✨","title":"취향 큐레이터","description":"일행의 취향을 읽고 오래 기억에 남을 장소와 장면을 골라요."}'),
    ('SNA', '🏄', '일단 뛰어들어, 파도잉', '날씨 보고 그날 정해서 자연 활동에 몸을 던지는 여행 스타일', 'character_sna', '["# 당일 결정","# 자연 돌진","# 활동","# 에너지 폭발"]', '["날씨와 컨디션에 맞춰 유연하게 정해요.","처음 해보는 활동도 겁내지 않아요.","현장에서 좋은 기회를 잘 잡아요.","함께 가는 사람에게 활력을 줘요."]', '["준비가 부족해 곤란해질 수 있어요.","예약이 필요한 활동을 놓칠 수 있어요.","체력을 과하게 쓰고 지칠 수 있어요.","안전 점검을 소홀히 할 수 있어요."]', '[{"code":"PNA","emoji":"⛰️","name":"정상까지 계획대로, 등반잉"},{"code":"SNR","emoji":"🌅","name":"발길 닿는 대로, 노을잉"}]', '{"icon":"⚡","title":"도전 점화 담당","description":"새로운 활동을 먼저 제안하고 망설이는 일행에게 용기를 더해요."}'),
    ('SNR', '🌅', '발길 닿는 대로, 노을잉', '목적지 없이 흘러가다 마음에 드는 풍경 앞에 오래 머무는 여행 스타일', 'character_snr', '["# 무계획","# 풍경 멍","# 자유 영혼","# 노을 수집"]', '["정해진 일정 없이 마음 가는 대로 움직여요.","우연히 만난 장소를 깊이 즐겨요.","서두르지 않고 순간에 집중해요.","어떤 상황이든 편하게 받아들여요."]', '["숙소나 교통편을 못 구할 수 있어요.","가고 싶던 곳을 놓치고 돌아올 수 있어요.","이동에 시간을 많이 쓸 수 있어요.","함께 가는 사람이 불안해할 수 있어요."]', '[{"code":"PNR","emoji":"🏞️","name":"한적한 곳만 골라, 힐링잉"},{"code":"SNA","emoji":"🏄","name":"일단 뛰어들어, 파도잉"}]', '{"icon":"🌅","title":"여유 안내자","description":"서두르는 분위기를 풀고 우연히 만난 풍경을 함께 즐기게 해요."}'),
    ('SCA', '🔥', '그날 끌리는 대로, 인싸잉', '계획은 최소로, 눈앞의 도시를 에너지 넘치게 누비는 여행 스타일', 'character_sca', '["# 즉흥 출발","# 도시 탐험","# 하루 꽉꽉","# 에너지 만렙"]', '["그날의 분위기에 맞춰 바로 움직여요.","처음 가는 골목도 망설이지 않아요.","현지에서 얻은 정보를 잘 활용해요.","밤낮없이 하루를 꽉 채워요."]', '["인기 장소는 대기가 길 수 있어요.","동선이 겹쳐 시간을 낭비할 수 있어요.","예산을 초과하기 쉬워요.","무리한 일정으로 다음 날이 힘들어져요."]', '[{"code":"PCA","emoji":"🏙️","name":"도시 구석까지 훑어, 완주잉"},{"code":"SCR","emoji":"☕","name":"골목 따라 흘러가, 유랑잉"}]', '{"icon":"🎉","title":"분위기 점화 담당","description":"재미있는 제안을 먼저 꺼내고 모두가 움직일 에너지를 만들어요."}'),
    ('SCR', '☕', '골목 따라 흘러가, 유랑잉', '걷다가 끌리는 가게에 들어가 반나절을 흘려보내는 여행 스타일', 'character_scr', '["# 골목 산책","# 카페 순례","# 여유 만끽","# 숨은 곳 발견"]', '["계획 없이도 좋은 가게를 잘 발견해요.","한 자리에서 오래 머물며 쉬어가요.","도시의 분위기를 천천히 흡수해요.","일정에 쫓기지 않아 마음이 편해요."]', '["유명 명소를 지나칠 수 있어요.","하루 동선이 좁은 범위에 머물러요.","문 닫은 가게에 헛걸음할 수 있어요.","여행 기록이 비슷비슷해질 수 있어요."]', '[{"code":"PCR","emoji":"🎨","name":"감성 스팟만 모아, 큐레잉"},{"code":"SCA","emoji":"🔥","name":"그날 끌리는 대로, 인싸잉"}]', '{"icon":"☕","title":"숨은 공간 발견자","description":"골목의 작은 가게와 쉬어갈 자리를 발견해 여행에 여백을 더해요."}');

-- 서버 제공 기능에 맞춘 한국어 이용약관과 개인정보처리방침이다.
INSERT INTO legal_documents
    (document_id, title, version, effective_date, publication_status, summary, review_notice, sections)
VALUES
    ('terms-of-service', '가야디 이용약관', '2.0.0', DATE '2026-08-13', 'PUBLISHED', '가야디 여행 성향검사와 여행 계획 기능을 이용할 때 필요한 사항을 안내합니다.', NULL,
     '[{"title":"제1조 목적","body":"이 약관은 가야디가 제공하는 여행 성향검사, 여행 계획, 초대, 일정, 장소 찜, 경로 추천 기능의 이용 조건을 정합니다."},{"title":"제2조 계정과 보안","body":"이용자는 자신의 계정과 로그인 정보를 안전하게 관리해야 하며, 초대 코드를 공유할 때 공개 범위를 확인해야 합니다."},{"title":"제3조 여행 성향검사","body":"9개 문항으로 계산한 8개 여행 유형은 여행 준비를 돕는 참고 자료이며 전문 심리검사나 의학적 판단이 아닙니다."},{"title":"제4조 추천 정보의 한계","body":"일정, 장소, 경로 추천은 참고 정보입니다. 영업시간, 예약, 교통, 날씨, 안전 상황은 출발 전에 공식 정보로 확인해야 합니다."},{"title":"제5조 금지행위","body":"타인의 정보를 무단으로 사용하거나 서비스의 정상 작동을 방해하거나 과도한 자동 요청을 보내서는 안 됩니다."},{"title":"제6조 서비스 변경","body":"운영자는 안정성 개선, 점검, 외부 서비스 변경으로 기능을 변경하거나 중단할 수 있으며 중요한 변경은 문서의 버전과 시행일을 갱신해 알립니다."},{"title":"제7조 준거법","body":"이 약관은 대한민국 법령을 따르며 분쟁은 협의를 우선하고 해결되지 않으면 관련 법령이 정한 법원에서 해결합니다."}]'),
    ('privacy-policy', '가야디 개인정보처리방침', '2.0.0', DATE '2026-08-13', 'PUBLISHED', '가야디가 서비스 제공을 위해 처리하는 정보와 이용자의 권리를 안내합니다.', NULL,
     '[{"title":"1. 처리 목적","body":"계정 인증, 프로필 표시, 여행 성향 결과 제공, 여행·참여자·초대·일정·찜 기능 제공, 서비스 안정성 확보를 위해 필요한 정보를 처리합니다."},{"title":"2. 처리하는 항목","body":"이메일, 암호화된 비밀번호, 닉네임, 소개, 프로필 이미지 주소, 여행 성향 결과, 여행·참여자·초대·일정·찜 정보를 처리합니다. 비밀번호 원문은 저장하지 않습니다."},{"title":"3. 성향검사 응답","body":"9개 문항의 선택값과 계산된 성향 결과를 여행 추천과 그룹 성향 분석을 위해 처리합니다."},{"title":"4. 보유 기간","body":"계정과 여행 정보는 회원 탈퇴 또는 이용자의 삭제 요청 때까지 보유합니다. 법령이 보존을 요구하는 정보는 해당 기간 동안 분리해 보관합니다."},{"title":"5. 외부 맞춤 추천 처리","body":"외부 맞춤 추천 기능은 이용자가 요청할 때 별도로 동의한 경우에만 성향 설명과 검색어를 추천 모델 제공자에게 전송합니다. 정확한 위치 좌표는 외부 추천 모델에 보내지 않으며, 동의하지 않아도 여행·일정·장소 조회 기능을 이용할 수 있습니다."},{"title":"6. 파기 방법","body":"보유 기간이 끝나거나 처리 목적을 달성한 정보는 복구할 수 없는 방법으로 지체 없이 파기합니다."},{"title":"7. 이용자의 권리","body":"이용자는 자신의 정보를 열람·정정·삭제하고 처리 정지를 요청할 수 있습니다. 본인 확인이 필요할 수 있습니다."},{"title":"8. 안전성 확보 조치","body":"암호화된 통신, 비밀번호 단방향 해시, 접근 권한 통제, 초대 코드 만료와 일회성 처리 등 필요한 보호 조치를 적용합니다."},{"title":"9. 문의와 변경","body":"개인정보 관련 문의 창구는 정식 출시 전 안내합니다. 방침이 변경되면 버전, 시행일, 주요 변경 내용을 서비스에서 알립니다."}]');

INSERT INTO regions (name, latitude, longitude, created_at, updated_at)
SELECT '제주', 33.4996213, 126.5311884, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM regions WHERE name = '제주');
