-- 친구 관계는 두 사용자 번호를 작은 값부터 저장해 요청 방향과 관계없이 한 건만 허용한다.
CREATE TABLE friendships (
    id              BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_user_id   BIGINT      NOT NULL,
    second_user_id  BIGINT      NOT NULL,
    requester_id    BIGINT      NOT NULL,
    blocked_by      BIGINT,
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                        CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'BLOCKED')),
    version         INT         NOT NULL DEFAULT 0,
    decided_at      TIMESTAMP,
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_friendship_first_user FOREIGN KEY (first_user_id) REFERENCES users (id),
    CONSTRAINT fk_friendship_second_user FOREIGN KEY (second_user_id) REFERENCES users (id),
    CONSTRAINT fk_friendship_requester FOREIGN KEY (requester_id) REFERENCES users (id),
    CONSTRAINT fk_friendship_blocker FOREIGN KEY (blocked_by) REFERENCES users (id),
    CONSTRAINT ck_friendship_user_order CHECK (first_user_id < second_user_id),
    CONSTRAINT ck_friendship_requester CHECK (requester_id IN (first_user_id, second_user_id)),
    CONSTRAINT ck_friendship_blocker CHECK (blocked_by IS NULL OR blocked_by IN (first_user_id, second_user_id)),
    CONSTRAINT ck_friendship_blocked_status CHECK (
        (status = 'BLOCKED' AND blocked_by IS NOT NULL)
        OR (status <> 'BLOCKED' AND blocked_by IS NULL)
    ),
    CONSTRAINT uk_friendship_users UNIQUE (first_user_id, second_user_id)
);

CREATE INDEX idx_friendships_first_status
    ON friendships (first_user_id, status, updated_at);
CREATE INDEX idx_friendships_second_status
    ON friendships (second_user_id, status, updated_at);
CREATE INDEX idx_friendships_requester_status
    ON friendships (requester_id, status);
